- cbrain_task/civet/portal/civet.rb
- cbrain_task/civet_combiner/portal/civet_combiner.rb
- cbrain_task/civet_qc/portal/civet_qc.rb
- cbrain_task/dcm2mnc/portal/dcm2mnc.rb
- cbrain_task/dcm2nii/portal/dcm2nii.rb
- cbrain_task/fsl_bedpostx/portal/fsl_bedpostx.rb
- cbrain_task/fsl_bet/portal/fsl_bet.rb
- cbrain_task/fsl_fast/portal/fsl_fast.rb
- cbrain_task/fsl_feat/portal/fsl_feat.rb
- cbrain_task/fsl_first/portal/fsl_first.rb
- cbrain_task/fsl_flirt/portal/fsl_flirt.rb
- cbrain_task/fsl_melodic/portal/fsl_melodic.rb
- cbrain_task/fsl_probtrackx/portal/fsl_probtrackx.rb
- cbrain_task/fsl_randomise/portal/fsl_randomise.rb
- cbrain_task/minc_convert/portal/minc_convert.rb
- cbrain_task/mnc2nii/portal/mnc2nii.rb
- cbrain_task/nii2mnc/portal/nii2mnc.rb
- cbrain_task/nu_correct/portal/nu_correct.rb
- cbrain_task/recon_all/portal/recon_all.rb
- cbrain_task/recon_all_longi/portal/recon_all_longi.rb
Ports all self.properties methods to the new (simpler) directive version
and adds support for the new :readonly_input_files property which
indicates that a task does not alter its input files (and can thus be
executed on files the user does not have write access to).
Requires https://github.com/remibernard/cbrain/commit/aea4978b76bb121942d8139a8ca6610ab3d8234f
> Readonly input files property, property directives

- userfiles/civet_study/views/_civet_study.html.erb
- userfiles/civet_study/views/_qc_file.html.erb
The javscript code has been tweaked a bit to make it easier
to understandm but it's still awful and still generates
tons of spurious requests before it quicks in a fixes
all the SRC attributes of the images.
Note: to see the diffs, we also need a special modification to the userfiles_controller on the main CBRAIN project. To be forthcoming. Maybe wait until that change has been incorported in the dev branch over there before reviewing this code.
The necessary platform code is included in https://github.com/aces/cbrain/pull/393 ; so wait until that PR is merged before trying out this one.
> Improved the appearance of the CivetStudy QC view.

- cbrain_task_descriptors/ICA-AROMA.json
Updates ICA-AROMA to the new container syntax.
Note that this must be used *only* after aces/cbrain#550 is merged. If used without those cbrain updates, ICA-AROMA will fail; conversely, if the old descriptor is used, it will fail with the newer cbrain version.
> Updating ICA-AROMA

- cbrain_task/civet/bourreau/civet.rb
The control script created by CBRAIN now prints
the logs of the failed stages.
> CIVET prints logs of failed stages in stdout.

- cbrain_task_descriptors/ICA-AROMA.json
- cbrain_task_descriptors/fsl_anat.json
- cbrain_task_descriptors/fsl_bet.json
- cbrain_task_descriptors/fsl_fast.json
- cbrain_task_descriptors/fsl_first.json
- cbrain_task_descriptors/fsl_probtrackx2.json
- cbrain_task_descriptors/fsl_sub.json
- cbrain_task_descriptors/mincbet.json
For upgrade to boutiques 0.5 in CBRAIN
@glatard can you take a look to fsl probtrackx. I had the following when doing the conversion: 
` InputError: "forcedir" should not be required`
`InputError: "outputpath" should not be required`
` InputError: "pathdistribution" should not be required`
`InputError: "outseeds" should not be required`
> Updated descriptor for boutiques 0.5

- cbrain_task/civet/bourreau/civet.rb
In the case where CIVET is run in a container, we
don't have access to the mincinfo program. So
if mincinfo is not available we will not validate
the minc file and proceed with the processing anyway.
> CIVET will skip validations if no mincinfo

- cbrain_task_descriptors/fsl_sub.json
In order to be compliant to Boutiques schema 0.5.12, I had to add an optional output-files.
> Fix schema descriptor (added optional output file)

- lib/datalad_data_provider.rb
- userfiles/datalad_system_subset/datalad_system_subset.rb
This was developed at a BrainHack in June 2018, by Natacha and I.
This PR makes the code a little bit more production-ready.
When browsing, the Datalad root repo is cloned in a userfile's cache located on our neat ScratchDataProvider. That userfile itself has a new proper `DataladSystemSubset` type too.
Missing: we have support for prefix subpath when synchronizing but not when browsing and registering. This means we can configure a DP that points to a directory "/a/b/c" and get all the entries directly under that path properly, but it would be nice to browse and register something deeper under (e.g. "/a/b/c/d/e") and have the userfile registered with the value "d/e" in its meta-data. See the method datalad_relative_path() for more info. Right now such a deeper file can still be …
> Datalad DataProvider

- cbrain_task_descriptors/ICA-AROMA.json
- cbrain_task_descriptors/fsl_bet.json
- cbrain_task_descriptors/fsl_fast.json
- cbrain_task_descriptors/fsl_first.json
- cbrain_task_descriptors/fsl_probtrackx2.json
Published the following descriptors to Zenodo as per https://github.com/boutiques/boutiques/issues/174:
* https://zenodo.org/record/1445789
* https://zenodo.org/record/1450991
* https://zenodo.org/record/1482743
* https://zenodo.org/record/1494308
* https://zenodo.org/record/1494312
Added to each descriptor:
* Author (used the ones from https://brainhack101.github.io/neurolinks/)
* Tags
* Descriptor URL (except for ICA-AROMA because we decided to add them after I had published that one)
Added container image and tests to fsl_bet, fsl_fast and fsl_first
Switched the order of paths in `path-template-stripped-extensions` for fsl_first because I noticed a bug where, for a file like `file_name.nii.gz`, it would see the `.nii` first and strip that so the file becomes `file_name.gz`
> Updated task descriptors according to what was published on Zenodo

- lib/datalad_data_provider.rb
- lib/datalad_repository.rb
- lib/tests/check_dl_dp.rb
We can navigate and get the metadata for the files in a file collection. Still only works for reading and will be associated with a pull request to the main repo that alters the database as now there are two new variables that need to be defined for a datalad repo.
> Updating the datalad data provider to now use a class that maintains a cached version of the repo.

- userfiles/minc_file/views/_info_header.html.erb
I discovered that some people put text information in non-UTF8 format in the text fields of some minc files, so that when we were trying to show the output of mincheader we got encoding errors in the templates.
This should fix that, we already had a nice utility to guess encoding of strings, or force them if necessary.
> UTF8 support in mincfile viewer for info/header

- cbrain_task_descriptors/fsl_stats.json
This is a Boutiques descriptor for fslstats from the FSL toolbox. fslstats just writes statistics about its input file to stdout. The descriptor captures stdout in an output file. All the options of fslstats are described except `-K` as I'm not sure what it does. Descriptor has been tested with `bosh` but not in CBRAIN.
> Boutiques tool for fslstats

- lib/datalad_data_provider.rb
- lib/datalad_repository.rb
- lib/tests/check_dl_dp2.rb
The caching system and overall architecture was
redesigned to properly handle any subpath that
is registered as a userfile. (The previous code
only worked when under a dl repo was another dl repo)
A new feature is that the admin can elect to cache
the DP repo using the CBRAIN caching system local
on each RemoteResource, or to register a DataladSystemSubset
as a standard userfile to hold the cache (and in this
case it will benefit from the CBRAIN caching system
for transfering a copy of the repo between RRs)
This should be backwards compatible with existing
DataladDataProviders configured.
> New datalad data provider code.

- cbrain_task_descriptors/freesurfer_7_1_1.json
This option does not exist anymore in Recon-all 7.1. 
It runs in a separate *.sh script
> Remove -hippocampal-subfields-T1 option for Recon-all 7.1

- lib/datalad_data_provider.rb
For this to be usable, the CBRAIN codebase need
the browse_path capabilities. These are added in
a separate PR.
> DataladDataProvider has browse_path capabilities

- lib/boutiques_bids_single_subject_maker.rb
A full description is in the file.
To try it, use a descriptor that has not yet already been modified for single subjects. A true BIDSApp with
```json
"command-line": "toolname [BIDSDATASET] blah blah"
```
This is one step in having a generalized BIDSApp support framework.
> Added new module BoutiquesBidsSingleSubjectMaker

- boutiques_descriptors/hippunfold_1_0_0.json
- boutiques_descriptors/hippunfold_1_1_0.json
Default arg should be `--nolock`, instead of `--unlock`. Unlock won't actually run the workflow (will just unlock), whereas nolock will run the workflow without locking.
> Bugfix for snakemake locking

- cbrain_task/civet_macaque/bourreau/civet_macaque.rb
- cbrain_task/civet_macaque/portal/civet_macaque.rb
- cbrain_task/civet_macaque/views/_civet_macaque_file_from_list.html.erb
- cbrain_task/civet_macaque/views/_show_params.html.erb
- cbrain_task/civet_macaque/views/_task_params.html.erb
Always launch multispectral and spectral_mask if selected on the main level.
Remove the ability to select or de-select in the table.
> [FIX] multispectral and spectral_mask

- boutiques_descriptors/hippunfold_1_2_0.json
We have a new release of hippunfold (v1.2.0), so I have adapted the v1.1.0 boutiques descriptor, and since it has now been published so I have updated the tool description within.
> Upgrading Hippunfold to v1.2.0

- userfiles/minc_file/views/_volume_viewer.html.erb
2 bug fixes here: 
- Put the `overlay` div outside of the `overlay-selection` div. In order to keep the `overlay-selection` div available once the volume is loaded. 
- Fix the selector for the files to overlay, remove the current file name (to avoid overlay of same volume), add a blank option to start.
> Fix OV for BB volumes

- boutiques_descriptors/physio_cbrain.json
- userfiles/physio_output/physio_output.rb
- userfiles/tapas_physio_output/tapas_physio_output.rb
Note to Natacha - I changed the image version from 8.1.0 (physIO version) to 1.2.0 (wrapper version). I considered changing my versioning scheme to match the tool version as per Pierre's earlier comment, but finally I think it's best too keep my wrapper-based versioning scheme for my images (the tool version is still in the descriptor and that is what is shown to the user at launch).
The main changes in this patch are fixing memory issues and throwing exceptions on bad input.
> [UPDATE] PhysIO wrapper 1.2.0

- boutiques_descriptors/deepprep_24_1_2.json
Basic descriptor for deepprep.
> Deepprep descriptor
