- cbrain_task_descriptors/ICA-AROMA.json
- cbrain_task_descriptors/fsl_anat.json
> Adding support for ICA-AROMA

- README.md
- userfiles/bids_dataset/bids_dataset.rb
- userfiles/bids_dataset/views/_bids_validator.html.erb
- userfiles/bids_dataset/views/_qc_panel.html.erb
Not very sure about my JavaScript but it works...
> Basic support for BIDS datasets

- userfiles/mgh_file/views/_qc_panel.html.erb
- userfiles/minc_file/views/_qc_panel.html.erb
- userfiles/minc_file/views/_volume_viewer.html.erb
- userfiles/minc_file/views/public/stylesheets/volume_viewer.css
- userfiles/nifti_file/views/_qc_panel.html.erb
Add qc_panel for MINC/NIfTI and MGH files.
It need some adjustment in the: 
- userfiles/minc_file/views/_volume_viewer.html.erb by adding `userfile_id` to all the html identifier.
In same time I fixed https://github.com/aces/cbrain/issues/369.
> Add Minc/NIfTI/MGH qc_panel

- cbrain_task/civet/bourreau/civet.rb
- cbrain_task/civet/common/civet.rb
- cbrain_task/civet/portal/civet.rb
- cbrain_task/civet/views/_deprecated_warning.html.erb
- cbrain_task/civet/views/_show_params.html.erb
- cbrain_task/civet/views/_task_params.html.erb
Now uses the CBRAIN built-in parallelizer.
> CIVET task de-parallelized.

- cbrain_task/civet/bourreau/civet.rb
> Fix missing conversion to name in CIVET

- cbrain_task/civet/portal/civet.rb
- cbrain_task/fsl_melodic/bourreau/fsl_melodic.rb
Also fixed one `rescue Exception`.
> Removed attribute 'launch_time'.

- cbrain_task/civet/bourreau/civet.rb
This should fix the issue on Bourreau side for CIVET 2.1.0
> Fix for CIVET prefix on bourreau side

- cbrain_task/civet/common/civet.rb
Just change the walltime to work properly with new version of CIVET.
> Change walltime once again.

- userfiles/civet_output/civet_output.rb
- userfiles/civet_output/views/_surface_viewer.html.erb
Moved Ruby code out of the view and into the model
> Surface Viewer Code Move

- cbrain_task/nii2mnc/portal/nii2mnc.rb
Fixes #44. Also updated regex for security
> Checks for Voxel Sign when format is Default

- cbrain_task/fsl_randomise/bourreau/fsl_randomise.rb
- cbrain_task/fsl_randomise/portal/fsl_randomise.rb
- cbrain_task/fsl_randomise/views/_task_params.html.erb
Based on user´s comments: 
- The mask is now optional.
- Added some options (--T2, -D)
- Fixed ´-c´ option.
> Improve fsl_randomise (mask is optionnal + more options)

- cbrain_task/fsl_randomise/views/_task_params.html.erb
- cbrain_task/fsl_randomise/views/public/edit_params_help.html
This is to fix the bug in Randomise UI that appear after the following [PR](https://github.com/aces/cbrain/pull/520).
> Fixed randomise mask/list UI.

- cbrain_task/bids_app_handler/bourreau/bids_app_handler.rb
- cbrain_task/civet/portal/civet.rb
- cbrain_task/civet_combiner/portal/civet_combiner.rb
- cbrain_task/civet_qc/portal/civet_qc.rb
- cbrain_task/recon_all/portal/recon_all.rb
- cbrain_task/recon_all_longi/portal/recon_all_longi.rb
* BidsAppHandler (using Boutiques integrator convention)
* Civet
* CivetQC
* CivetCombiner
* ReconAll
* ReconAllLongi
> Added zenodo outputs for some task

- lib/datalad_repository.rb
This new code will handle better the cases when dataset files are already present/installed/downloaded.
To test: browse a datalad dp, and synchronize one file. Then artifically make the local copies of both 'ancient' and get CBRAIN to redownload the information.
Before this patch: the browse data will not be updated and the sync to cache will crash.
After the patch: the browse data will be updated and the sync to cache will resync everyhting.
This will be (the only) part of  https://github.com/aces/cbrain/issues/856
> Improved datalad data provider.

- cbrain_task_descriptors/fsl_anat.json
This adds the container information to the JSON descriptor of `fsl_anat` so that `fsl_anat`.
> Add the container information to the json descriptor of fsl_anat

- cbrain_task_descriptors/freesurfer_7_1_1.json
FreeSurfer descriptor as it is after Zenodo publishing.
> [FIX] FreeSurfer descriptor

- cbrain_task_descriptors/fsl_stats.json
Generate output name based on input name.
> [FIX] fslstats output naming

- cbrain_task/civet/portal/civet.rb
- cbrain_task/civet_macaque/portal/civet_macaque.rb
> [FIX] search of *t2, *mask... for CIVET

- cbrain_task_descriptors/deform_sim.json
What do you think of this tool?
> Deformation Simulation tool

- lib/boutiques_freesurfer_license_finder.rb
Requires the new integrator and the new CBRAIN codebase
of today with special module inclusion.
> Auto find and assign FreesurferLicense files

- cbrain_task/civet_macaque/bourreau/civet_macaque.rb
- cbrain_task/civet_macaque/portal/civet_macaque.rb
- cbrain_task/civet_macaque/views/_civet_macaque_file_from_list.html.erb
- cbrain_task/civet_macaque/views/_show_params.html.erb
- cbrain_task/civet_macaque/views/_task_params.html.erb
Fix little bug on CIVET-Macaque + add some JS code to handle exclusion between parameters.
> Civet macaque

- cbrain_task/civet_macaque/views/_civet_macaque_file_from_list.html.erb
> [FIX] Civet macaque bug

- userfiles/minc_file/views/_volume_viewer.html.erb
> [FIX] value display in BrainBrowser Volume viewer

- boutiques_descriptors/explore-asl.json
- boutiques_descriptors/oxford_asl.json
- boutiques_descriptors/physio_cbrain.json
2nd try at PR. Only 2 commits (1 per descriptor) this time. Not sure why previous oxasl commits were showing up in the PR before.
PhysIO descriptor is renamed and added to boutiques_descriptors rather than cbrain_task_descriptors.
> xASL and PhysIO descriptor updates

- userfiles/mgh_file/views/_volume_viewer_loader.html.erb
- userfiles/minc_file/views/_volume_viewer.html.erb
- userfiles/minc_file/views/_volume_viewer_loader.html.erb
- userfiles/nifti_file/views/_volume_viewer_loader.html.erb
> [FIX] BB viewer for QC panel

- boutiques_descriptors/mcflirt.json
Add descriptor for [MCFLIRT](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/MCFLIRT)
> [ADD] MCFLIRT descriptor

- lib/boutiques_bids_subject_subsetter.rb
Fix Boutiques BIDS subject subsetter
> [FIX] BBSS boutiques module

- cbrain_task/civet_macaque/portal/civet_macaque.rb
- cbrain_task/civet_macaque/views/_task_params.html.erb
> Civet macaque load preset

- lib/datalad_data_provider.rb
- lib/datalad_repository.rb
- openneuro/README.txt
- openneuro/app/controllers/open_neuro_controller.rb
- openneuro/app/models/open_neuro.rb
- openneuro/app/views/open_neuro/_about_logged_in.html.erb
- openneuro/app/views/open_neuro/_about_not_logged_in.html.erb
- openneuro/app/views/open_neuro/show.html.erb
- openneuro/config/openneuro_routes.rb
- openneuro/install.sh
Automatic configuration of OpenNeuro datasets in CBRAIN.
> OpenNeuro support code

- boutiques_descriptors/micapipe_0_2_3.json
Added new descriptor for [Micapipe 2.3](https://github.com/MICA-MNI/micapipe/releases/tag/v0.2.3)
> [ADD] Micapipe 2_3

- boutiques_descriptors/micapipe_0_2_2.json
[ADD] flags
- PROC_ASL 
- ASL_SCAN_STR
-  M0_SCAN_STR
- FILTER
- MAIN_SCAN_RUN
- PHASE_REVERSAL_RUN
[FIX]
-add free surfer to Surface Processing
-change the default value of tracts from 10m into 40m (typo)
> fix errors in 0.2.2 json

- cbrain_task/civet/portal/civet.rb
- cbrain_task/civet_macaque/portal/civet_macaque.rb
- cbrain_task/dcm2mnc/portal/dcm2mnc.rb
- cbrain_task/dcm2nii/portal/dcm2nii.rb
- cbrain_task/fsl_randomise/portal/fsl_randomise.rb
See https://github.com/aces/cbrain/issues/1454
> refactor raw_first_column into pluck

- userfiles/minc_file/views/_volume_viewer.html.erb
- userfiles/minc_file/views/public/stylesheets/volume_viewer.css
Added a select box to change volume viewer canvas size. 
It come with a little PR in the Main CBRAIN for the QC table here: [https://github.com/aces/cbrain/pull/1543](https://github.com/aces/cbrain/pull/1543)
> [ADD] ability to change panel size

- boutiques_descriptors/deepprep_24_1_2.json
Clean version of deeprep adjustement
> [ADD] deeprep options
